### ISSUE TITLE
Onde posso encontrar a documentação da API do SUAP?

### ISSUE THREAD

**Issue by isaacmsl** [L-Marcel/myf#1]
Gostaria de desenvolver uma aplicação com Javascript e utilizando a API do SUAP, poderia me dar alguns detalhes?

**Comment by isaacmsl** [comment]
Existe alguma documentação disponível? Não encontrei em lugar algum! :confused:

**Comment by L-Marcel** [comment]
Opa, desculpe a demora para responder, ainda estou me acostumando a interface do Github. 

Se ainda precisar de ajuda, tente dá uma olhada nesse exemplo: [https://gitlab.devops.ifrn.edu.br/lrlucena/suap-api/commit/50b3437466fe7e4d76ad4d2d023635d4cd39bf6b](url)

Para requisitar mais informação do Suap, você pode encontrar os endereços aqui: 
[https://github.com/hdev14/fake-api](url)

Entretanto, desconheço a existência de uma documentação oficial.

**Comment by L-Marcel** [comment]
Caso queira mais detalhes, por favor entre em contato comigo via Discord (Pelo Github posso acabar demorando).  Usuário: !Lucas_Marcel#3484
